**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

**Como calcular desvio padrão:**
1. Calcule a média do conjunto de dados
2. Para cada valor do conjunto, calcule a distância que ele se encontra do valor médio
3. Eleve as diferenças ao quadrado (para evitar números negativos)
4. Calcule a média dos quadrados obtidos e tire a raiz do resultado

In [4]:
# Importação do numpy (só precisa ser feita uma única vez no documento)
import numpy as np
# Cria um array apartir da função de aleatório do numpy -> argumentos (minimo, maximo, tamanho)
array = np.random.randint(1, 100, 50)
# Para calcular a média é usada a função mean()
media = np.mean(array)
# Para calcular a mediana é usada a função median()
mediana = np.median(array)
# Para calcular o desvio padrão é usada a função std()
desvioPadrao = np.std(array)
# Para encontrar o valor máximo de um conjunto de dados
maximo = np.max(array)
# Para encontrar o valor mínimo de um conjunto de dados
minimo = np.min(array)
# Saídas em tela
print(array)
print(f"A média é: {media}")
print(f"A mediana é: {mediana}")
print(f"O desvio padrão é: {desvioPadrao}")
print(f"O valor máximo é: {maximo}")
print(f"O valor mínimo é: {minimo}")


[13 87 88 44  3 65 69 73 66 42 40 37 48 82 78  4 29 80 44 34 33 97  5 30
 60 90 91 40 76 73 49 79 39 94 43 27 64 11 46 36 55 86 53 55 17 99 17 68
 68 18]
A média é: 52.9
A mediana é: 51.0
O desvio padrão é: 26.79272289260649
O valor máximo é: 99
O valor mínimo é: 3


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [10]:
# Criação de um array multidimensional, nesse caso, o argumento "tamanho" é informado entre ()
matriz1 = np.random.randint(1, 10, (3,3))
matriz2 = np.random.randint(1, 10, (3,3))
# Operação de soma entre as duas matrizes(arrays multimensionais) criadas
soma = matriz1 + matriz2
# Operação de subtração entre as duas matrizes(arrays multimensionais) criadas
subtracao = matriz1 - matriz2
# Operação de multiplicação entre as duas matrizes(arrays multimensionais) criadas
multiplicacao = matriz1 * matriz2
# Operação de divisão entre as duas matrizes(arrays multimensionais) criadas
divisao = matriz1 / matriz2

# Saídas em tela
print(f"Matriz 1\n{matriz1}")
print(f"Matriz 2\n{matriz2}")
print(f"Soma\n {soma}")
print(f"Subtração\n {subtracao}")
print(f"Multiplicação\n {multiplicacao}")
print(f"Divisão\n {divisao}")



Matriz 1
[[1 6 1]
 [1 9 3]
 [3 3 9]]
Matriz 2
[[4 5 1]
 [2 5 4]
 [8 5 2]]
Soma
 [[ 5 11  2]
 [ 3 14  7]
 [11  8 11]]
Subtração
 [[-3  1  0]
 [-1  4 -1]
 [-5 -2  7]]
Multiplicação
 [[ 4 30  1]
 [ 2 45 12]
 [24 15 18]]
Divisão
 [[0.25  1.2   1.   ]
 [0.5   1.8   0.75 ]
 [0.375 0.6   4.5  ]]


**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [13]:
# Criação de uma matriz (array multidimensional)
matriz = np.random.randint(1, 20, (4,4))
# Para somar apenas os valores das linhas da matriz o valor do axis deve ser 1
soma_linha = np.sum(matriz, axis=1)
# Para somar apenas os valores das colunas da matriz o valor do axis deve ser 0
soma_coluna = np.sum(matriz, axis=0)

# Saídas em tela
print(f"Matriz\n{matriz}")
print(f"Soma linhas: {soma_linha}")
print(f"Soma colunas: {soma_coluna}")

Matriz
[[ 5  8  1 13]
 [13 10  1 11]
 [18 14 13 11]
 [ 2 17 16 11]]
Soma linhas: [27 35 56 46]
Soma colunas: [38 49 31 46]


**TESTE**

**É possível somar matriz multidimensional (3D+)?**

In [17]:
teste = np.random.randint(1, 10, (3,3,3))
soma_linhas = np.sum(teste, axis = 1)
soma_colunas = np.sum(teste, axis=0)
soma_teste = np.sum(teste, axis = 2)

print(f"Matriz original:\n {teste}")
print(f"Soma linhas: {soma_linhas}")
print(f"Soma colunas: {soma_colunas}")
print(f"Soma teste: {soma_teste}")

Matriz original:
 [[[8 3 4]
  [3 8 5]
  [5 9 2]]

 [[9 8 7]
  [6 9 7]
  [5 7 7]]

 [[4 3 4]
  [2 8 2]
  [6 3 6]]]
Soma linhas: [[16 20 11]
 [20 24 21]
 [12 14 12]]
Soma colunas: [[21 14 15]
 [11 25 14]
 [16 19 15]]
Soma teste: [[15 16 16]
 [24 22 19]
 [11 12 15]]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [15]:
# Criação de um array unidimensional
array = np.random.randint(0, 50, 30)
# Filtro dentro da própria array
valores_maiores = array[array > 25]

# Saídas em tela
print(f"Array completo: {array}")
print(f"Array com valores maiores que 25: {valores_maiores}")

Array completo: [13  9 14  1 10 37 48 24 30 40  0 14 22 31 29 20  3 17  9 32 41  0 26 44
 38 31 32 37 36 13]
Array com valores maiores que 25: [37 48 30 40 31 29 32 41 26 44 38 31 32 37 36]


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

**Soma cumulativa:**

É a soma de cada elemento da array pelo seu anterior, exemplo:

*[a, b, c, d]*

Soma cumulativa:

*[a, b+a, c+b+a, d+c+b+a]*

In [16]:
# Criação de uma array multidimensional (3D)
matrizmulti = np.random.randint(1, 10, (3,3,3))
# Para calcular o soma total de uma matriz é utilizada a função sum()
soma_total = np.sum(matrizmulti)
# Para calcular o soma cumulativa de uma matriz é utilizada a função cumsum()
soma_cumulativa = np.cumsum(matrizmulti)

# Saídas em tela
print(f"Matriz:\n {matrizmulti}")
print(f"Soma total: {soma_total}")
print(f"Soma cumulativa: {soma_cumulativa}")

Matriz:
 [[[4 2 6]
  [9 5 8]
  [2 8 4]]

 [[9 8 3]
  [2 8 3]
  [1 8 1]]

 [[8 6 9]
  [8 8 3]
  [7 6 7]]]
Soma total: 153
Soma cumulativa: [  4   6  12  21  26  34  36  44  48  57  65  68  70  78  81  82  90  91
  99 105 114 122 130 133 140 146 153]
